baseURL = "https://ams.su/"
title = "Advanced Media Storage"
publishdir = "./docs"
defaultContentLanguage = "ru"
enableGitInfo = "true"

[permalinks]
  "post" = "/:filename"
  "page" = "/:filename"

[params]
  subtitle = "Видео со всего мира"
  description = "Смотреть видео онлайн бесплатно"
  googleTagManagerId = "GTM-A2CDIFG"

[languages]
  [languages.ru]
    languageName = "Русский"
    languageCode = "ru-ru"
    title = "Advanced Media Storage"
    weight = 1
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    title = "Advanced Media Storage"
    weight = 2

[taxonomies]
  tag = "tags"
  category = "category"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "JSON"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
